import { useCallback,useEffect,useMemo,useState } from 'react';
import { db,seedDatabase,type NexusSettings } from '../storage/db';
import type { Contact,Conversation,ConnectionState,EmergencyPacket,LocalIdentity,MessageEnvelope } from '../types';
import { encryptMessage } from '../crypto/encryption';
import { makeId } from '../utils/id';

export function useNexus(){
 const [identity,setIdentity]=useState<LocalIdentity|null>(null),[settings,setSettings]=useState<NexusSettings|null>(null),[conversations,setConversations]=useState<Conversation[]>([]),[messages,setMessages]=useState<MessageEnvelope[]>([]),[emergencies,setEmergencies]=useState<EmergencyPacket[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[connection,setConnection]=useState<ConnectionState>(navigator.onLine?'online':'offline'),[pwaInstalled,setPwaInstalled]=useState(false);
 const refresh=useCallback(async()=>{await seedDatabase();const [i,s,c,m,e,ct]=await Promise.all([db.getIdentity(),db.getSettings(),db.listConversations(),db.listMessages(),db.listEmergencies(),db.listContacts()]);setIdentity(i??null);setSettings(s??null);setConversations(c.sort((a,b)=>b.lastAt-a.lastAt));setMessages(m.sort((a,b)=>a.createdAt-b.createdAt));setEmergencies(e.sort((a,b)=>b.createdAt-a.createdAt));setContacts(ct.sort((a,b)=>b.pairedAt-a.pairedAt));},[]);
 useEffect(()=>{void refresh();const on=()=>setConnection('online'),off=()=>setConnection('offline');addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[refresh]);
 const setRelayEnabled=useCallback(async(enabled:boolean)=>{if(!settings)return;const n={...settings,relay:{...settings.relay,enabled}};setSettings(n);await db.saveSettings(n)},[settings]);
 const setBatteryLimit=useCallback(async(v:number)=>{if(!settings)return;const n={...settings,relay:{...settings.relay,batteryLimit:v}};setSettings(n);await db.saveSettings(n)},[settings]);
 const sendMessage=useCallback(async(id:string,text:string)=>{if(!identity||!text.trim())return;const now=Date.now(),enc=await encryptMessage(text.trim());const c=conversations.find(x=>x.id===id);const env:MessageEnvelope={id:makeId('msg'),conversationId:id,senderId:identity.id,recipientId:c?.contactId??'NEX-REMOTE',...enc,createdAt:now,expiresAt:now+86400000,ttl:6,maxHops:6,hops:0,status:connection==='online'?'queued':'queued',priority:'normal'};await db.saveMessage(env);if(c)await db.saveConversation({...c,lastMessage:text.trim(),lastAt:now,unread:0});await refresh();return env},[connection,conversations,identity,refresh]);
 const addContact=useCallback(async(name:string,publicId:string)=>{if(!name.trim()||!publicId.trim()||publicId===identity?.id)return;const id=`conv-${makeId('c')}`;const now=Date.now();const contact:Contact={id,name:name.trim(),publicId:publicId.trim(),createdAt:now,pairedAt:now};await db.saveContact(contact);await db.saveConversation({id,title:name.trim(),avatar:name.trim().slice(0,1).toUpperCase(),lastMessage:'Paired securely. Ready for messages.',lastAt:now,unread:0,online:true,contactId:publicId.trim()});await refresh();return id},[identity,refresh]);
 const createEmergency=useCallback(async(message:string,location?:{latitude:number;longitude:number})=>{const p:EmergencyPacket={id:makeId('sos'),message,createdAt:Date.now(),priority:'emergency',status:'queued',...location};await db.saveEmergency(p);await refresh();return p},[refresh]);
 const markFirstRunDone=useCallback(async()=>{if(!settings)return;const n={...settings,firstRunDone:true};await db.saveSettings(n);setSettings(n)},[settings]);
 const stats=useMemo(()=>({outbox:messages.filter(m=>m.status==='queued').length,storedBytes:messages.reduce((s,m)=>s+m.ciphertext.length,0)}),[messages]);
 return {identity,settings,conversations,messages,emergencies,contacts,connection,pwaInstalled,setPwaInstalled,refresh,setRelayEnabled,setBatteryLimit,sendMessage,addContact,createEmergency,markFirstRunDone,stats};
}
