import { useEffect,useMemo,useState } from 'react';
import { Icon } from '../components/Icon';
import { formatRelative,formatTime } from '../utils/id';
import { decryptMessage } from '../crypto/encryption';
import type { Conversation,MessageEnvelope } from '../types';
import { PairingModal } from '../components/PairingModal';

function MessageBody({message}:{message:MessageEnvelope}){const [text,setText]=useState('Encrypted packet');useEffect(()=>{let live=true;void decryptMessage(message.ciphertext,message.iv).then(v=>{if(live)setText(v)}).catch(()=>{if(live)setText('Encrypted packet')});return()=>{live=false}},[message.ciphertext,message.iv]);return <p>{text}</p>}

export function ChatsPage({conversations,messages,onSend,onPair,identity,openPairing=false,onPairingClose}:{conversations:Conversation[];messages:MessageEnvelope[];onSend:(id:string,text:string)=>Promise<unknown>;onPair:(name:string,id:string)=>Promise<unknown>;identity:any;openPairing?:boolean;onPairingClose?:()=>void}){
 const [selected,setSelected]=useState(conversations[0]?.id??'conv-a'),[text,setText]=useState(''),[query,setQuery]=useState(''),[attachment,setAttachment]=useState(false),[pairing,setPairing]=useState(openPairing),[call,setCall]=useState<'audio'|'video'|null>(null);
 useEffect(()=>{ setPairing(openPairing); },[openPairing]);
 const filtered=useMemo(()=>conversations.filter(c=>`${c.title} ${c.lastMessage}`.toLowerCase().includes(query.toLowerCase())),[conversations,query]);
 const current=conversations.find(c=>c.id===selected)??conversations[0]; const currentMessages=messages.filter(m=>m.conversationId===selected);
 return <div className="chat-layout"><aside className="chat-list panel"><div className="list-head"><div><p className="eyebrow">PRIVATE INBOX</p><h1>Chats</h1></div><a className="icon-btn add-contact-btn" aria-label="Add contact" title="Add contact" href="#/pair"><Icon name="plus"/></a></div><label className="search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search conversations"/></label><a className="pair-cta" href="#/pair"><span><Icon name="plus" size={16}/></span><div><b>New contact</b><small>Pair once with a QR code</small></div><Icon name="arrow" size={16}/></a><div className="conversation-list">{filtered.map(c=><button key={c.id} className={`conversation ${c.id===selected?'active':''}`} onClick={()=>setSelected(c.id)}><span className="avatar">{c.avatar}</span><span className="conversation-copy"><b>{c.title}</b><span>{c.lastMessage}</span></span><span className="conversation-meta"><small>{formatRelative(c.lastAt)}</small>{c.unread>0&&<em>{c.unread}</em>}</span></button>)}</div></aside>
 <section className="message-panel panel"><div className="chat-header"><div className="chat-person"><span className="avatar large">{current?.avatar??'N'}</span><div><b>{current?.title??'Conversation'}</b><span><span className={`presence ${current?.online?'online':''}`}/>{current?.online?'peer available':'offline-ready'}</span></div></div><div className="chat-actions"><button className="icon-btn" title="Audio call" onClick={()=>setCall('audio')}><Icon name="phone"/></button><button className="icon-btn" title="Video call" onClick={()=>setCall('video')}><Icon name="video"/></button><span className="secure-tag"><Icon name="shield" size={15}/> local encryption</span></div></div>
 <div className="message-stream"><div className="route-note"><span className="mini-node"/> {current?.online?'Peer transport available · messages queue locally first.':'Offline mode · messages are stored on this device until a transport returns.'}</div>{currentMessages.length===0&&<div className="empty"><div className="empty-orb"/><h3>No messages yet</h3><p>Write anything. NEXUS encrypts the message before saving it locally.</p></div>}{currentMessages.map(m=><article key={m.id} className={`bubble-row ${m.senderId.startsWith('NEX-')?'mine':''}`}><div className="bubble"><MessageBody message={m}/><footer><span>{formatTime(m.createdAt)}</span><span className={`message-status ${m.status}`}>{m.status}</span></footer></div></article>)}</div>
 <form className="composer" onSubmit={async e=>{e.preventDefault();if(!text.trim()||!selected)return;await onSend(selected,text);setText('')}}><button type="button" className={`icon-btn attachment ${attachment?'active':''}`} onClick={()=>setAttachment(v=>!v)}><Icon name="paperclip"/></button>{attachment&&<div className="attachment-menu"><button type="button">Photo</button><button type="button">File</button><button type="button">Contact</button></div>}<input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message…"/><button className="send-btn" type="submit"><Icon name="send" size={19}/></button></form></section>
 {pairing&&<PairingModal identity={identity} onPair={onPair} onClose={()=>{setPairing(false); onPairingClose?.();}}/>} {call&&<div className="modal-backdrop"><div className="modal call-modal"><div className="call-orb"><Icon name={call==='video'?'video':'phone'} size={28}/></div><p className="eyebrow">{call==='video'?'VIDEO':'AUDIO'} CALL</p><h2>{current?.title}</h2><p className="muted">NEXUS will use a peer-to-peer WebRTC transport when both devices have a reachable route. A website cannot reconnect two phones after all networking is gone.</p><div className="call-state"><span className="status-dot connecting"/> Waiting for peer transport…</div><button className="btn danger full" onClick={()=>setCall(null)}>END CALL</button></div></div>}
 </div>
}
