import { useState } from 'react';
import { Icon } from '../components/Icon';
import { Sparkline } from '../components/Sparkline';
import type { RelayStats } from '../types';
import { requestBluetooth } from '../services/capabilities';

export function RelayPage({ stats, enabled, batteryLimit, onToggle, onBattery }: { stats: RelayStats; enabled: boolean; batteryLimit: number; onToggle: (value: boolean) => Promise<void>; onBattery: (value: number) => Promise<void>; }) {
  const [bluetoothMessage, setBluetoothMessage] = useState('');
  return <div className="page-grid"><section className="hero panel relay-hero"><div><p className="eyebrow">CONSENTED FORWARDING</p><h1>Relay Mode</h1><p>Allow your device to temporarily forward encrypted packets for other consenting NEXUS users. The relay sees packet metadata and ciphertext, never message plaintext.</p></div><label className={`switch ${enabled ? 'on' : ''}`}><input type="checkbox" checked={enabled} onChange={(e) => void onToggle(e.target.checked)} /><span /><b>{enabled ? 'ON' : 'OFF'}</b></label></section>
  <section className="stats-grid"><div className="metric panel"><span>MESSAGES RELAYED</span><strong>{stats.messagesRelayed.toLocaleString()}</strong><small>this device</small><Sparkline values={[4,7,5,12,9,15,13,20]} /></div><div className="metric panel"><span>BYTES RELAYED</span><strong>{(stats.bytesRelayed/1024).toFixed(1)} KB</strong><small>ciphertext only</small><Sparkline values={[3,5,4,10,8,12,14,18]} /></div><div className="metric panel"><span>STORAGE USED</span><strong>{(stats.storageBytes/1024).toFixed(1)} KB</strong><small>temporary relay queue</small></div></section>
  <section className="panel relay-controls"><div className="section-head"><div><p className="eyebrow">DEVICE GUARDRAILS</p><h2>Relay policy</h2></div><Icon name="shield" /></div><label className="range-row"><span>Battery ceiling <b>{batteryLimit}%</b></span><input type="range" min="10" max="80" step="5" value={batteryLimit} onChange={(e) => void onBattery(Number(e.target.value))} /><small>Relay will remain voluntarily enabled only while your chosen limit is respected. Native background execution would require an app with platform permissions.</small></label><div className="capability"><div><b>Bluetooth capability check</b><span>Detect the real browser API — never fake mesh support.</span></div><button className="btn ghost" onClick={async () => setBluetoothMessage(await requestBluetooth())}>CHECK BLUETOOTH</button></div>{bluetoothMessage && <div className="notice"><Icon name="info" />{bluetoothMessage}</div>}</section>
  <section className="panel privacy-card"><Icon name="shield" size={26}/><div><h3>Relay privacy boundary</h3><p>Packets are AES-GCM encrypted before they enter the relay layer. The relay can manage TTL, expiration, duplicate IDs, and byte limits without obtaining plaintext. This browser prototype does not implement a full audited multi-party key-exchange system.</p></div></section></div>;
}
