import { useEffect,useMemo,useRef,useState } from 'react';
import { Icon } from './Icon';
import type { LocalIdentity } from '../types';

function payload(identity:LocalIdentity){return `nexus://pair?i=${encodeURIComponent(identity.id)}&n=${encodeURIComponent(identity.name)}&v=1`}
function qrUrl(value:string){return `https://api.qrserver.com/v1/create-qr-code/?size=420x420&margin=18&data=${encodeURIComponent(value)}`}

export function PairingModal({identity,onPair,onClose}:{identity:LocalIdentity|null;onPair:(name:string,id:string)=>Promise<unknown>;onClose:()=>void}){
 const [tab,setTab]=useState<'show'|'scan'>('show'),[name,setName]=useState(''),[code,setCode]=useState(''),[status,setStatus]=useState(''),video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null);
 const value=useMemo(()=>identity?payload(identity):'',[identity]);
 useEffect(()=>{if(tab!=='scan')return;let active=true;(async()=>{try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});stream.current=s;if(video.current)video.current.srcObject=s;const Detector=(window as any).BarcodeDetector;if(!Detector){setStatus('This browser cannot scan QR codes automatically. Paste the pairing code instead.');return}const detector=new Detector({formats:['qr_code']});while(active&&video.current){const found=await detector.detect(video.current);if(found[0]?.rawValue){setCode(found[0].rawValue);break}await new Promise(r=>setTimeout(r,350));}}catch(e){setStatus(e instanceof Error?e.message:'Camera permission was denied.')}})();return()=>{active=false;stream.current?.getTracks().forEach(t=>t.stop())}},[tab]);
 const pair=async()=>{try{const raw=code.trim();const u=new URL(raw);if(u.protocol!=='nexus:')throw new Error('Not a NEXUS pairing code.');const id=u.searchParams.get('i')||'';const n=u.searchParams.get('n')||'NEXUS contact';if(!id)throw new Error('Missing contact ID.');await onPair(name.trim()||n,id);setStatus('Contact paired locally.');setName('');}catch(e){setStatus(e instanceof Error?e.message:'Invalid pairing code.')}};
 return <div className="modal-backdrop" role="presentation"><div className="modal pairing-modal" role="dialog" aria-modal="true" aria-label="Pair a contact"><div className="modal-head"><div><h3>PAIR A CONTACT</h3><span className="modal-kicker">ONE-TIME INTERNET SETUP</span></div><button type="button" className="icon-btn" onClick={onClose}><Icon name="close"/></button></div><div className="pair-tabs"><button type="button" className={tab==='show'?'active':''} onClick={()=>setTab('show')}>MY QR</button><button type="button" className={tab==='scan'?'active':''} onClick={()=>setTab('scan')}>SCAN QR</button></div>{tab==='show'&&<div className="pair-show"><div className="qr-frame">{identity?<img src={qrUrl(value)} alt="NEXUS pairing QR"/>:<div className="qr-loading">Loading…</div>}</div><h2>Share this code</h2><p>It contains only your NEXUS public ID and display name. Do not put secrets in QR payloads.</p><div className="code-row"><code>{identity?.id}</code><button type="button" className="btn ghost" onClick={()=>navigator.clipboard?.writeText(value)}><Icon name="copy"/>COPY</button></div><div className="notice"><Icon name="wifi"/> Internet is used for this initial pairing flow. Your messages are kept locally after pairing.</div></div>} {tab==='scan'&&<div className="pair-scan"><div className="scanner"><video ref={video} autoPlay muted playsInline/><div className="scan-line"/></div><label>Pairing code<input value={code} onChange={e=>setCode(e.target.value)} placeholder="Paste nexus://pair?..."/></label><label>Your name for this contact<input value={name} onChange={e=>setName(e.target.value)} placeholder="Optional nickname"/></label><button className="btn primary full" onClick={()=>void pair()}><Icon name="qr"/>PAIR LOCALLY</button>{status&&<div className="notice"><Icon name="info"/>{status}</div>}</div>}</div></div>
}
